
export const BIBLE_BOOKS = {
  ko: [
    "창세기", "출애굽기", "레위기", "민수기", "신명기", "여호수아", "사사기", "룻기", "사무엘상", "사무엘하",
    "열왕기상", "열왕기하", "역대상", "역대하", "에스라", "느헤미야", "에스더", "욥기", "시편", "잠언",
    "전도서", "아가", "이사야", "예레미야", "예레미야애가", "에스겔", "다니엘", "호세아", "요엘", "아모스",
    "오바댜", "요나", "미가", "나훔", "하박국", "스바냐", "학개", "스가랴", "말라기",
    "마태복음", "마가복음", "누가복음", "요한복음", "사도행전", "로마서", "고린도전서", "고린도후서", "갈라디아서",
    "에베소서", "빌립보서", "골로새서", "데살로니가전서", "데살로니가후서", "디모데전서", "디모데후서", "디도서",
    "빌레몬서", "히브리서", "야고보서", "베드로전서", "베드로후서", "요한1서", "요한2서", "요한3서", "유다서", "요한계시록"
  ],
  en: [
    "Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy", "Joshua", "Judges", "Ruth", "1 Samuel", "2 Samuel",
    "1 Kings", "2 Kings", "1 Chronicles", "2 Chronicles", "Ezra", "Nehemiah", "Esther", "Job", "Psalms", "Proverbs",
    "Ecclesiastes", "Song of Solomon", "Isaiah", "Jeremiah", "Lamentations", "Ezekiel", "Daniel", "Hosea", "Joel", "Amos",
    "Obadiah", "Jonah", "Micah", "Nahum", "Habakkuk", "Zephaniah", "Haggai", "Zechariah", "Malachi",
    "Matthew", "Mark", "Luke", "John", "Acts", "Romans", "1 Corinthians", "2 Corinthians", "Galatians", "Ephesians",
    "Philippians", "Colossians", "1 Thessalonians", "2 Thessalonians", "1 Timothy", "2 Timothy", "Titus", "Philemon",
    "Hebrews", "James", "1 Peter", "2 Peter", "1 John", "2 John", "3 John", "Jude", "Revelation"
  ]
};

export const I18N = {
  ko: {
    appName: "GraceLog",
    home: "기록",
    calendar: "달력",
    report: "분석",
    settings: "설정",
    todayRecord: "오늘의 묵상",
    selectBook: "본문 선택",
    chapter: "장",
    verse: "절",
    reflection: "묵상 (Observation)",
    application: "적용 (Application)",
    prayer: "기도 (Prayer)",
    save: "저장하기",
    aiHelp: "AI 도움",
    premium: "프리미엄",
    free: "무료 플랜",
    premiumOnly: "프리미엄 기능",
    aiDisclaimer: "AI는 묵상을 돕는 참고용입니다. 본인의 고백을 담아보세요.",
    observation: "관찰",
    tags: "태그",
    share: "공유",
    summary: "요약",
    streak: "연속 기록",
    favorite: "북마크",
    noRecords: "기록이 아직 없어요.",
    searchPlaceholder: "키워드, 태그 검색...",
    templateType: "기본 템플릿",
    language: "언어 설정",
    sync: "데이터 동기화",
    weeklyReport: "주간 리포트",
    stats: "통계",
    recentTags: "자주 쓴 태그",
    verseRange: "절 범위 (예: 1-10)",
    switchPremium: "Premium 체험하기 (무료)",
    switchFree: "무료 플랜으로 변경",
    days: ["일", "월", "화", "수", "목", "금", "토"],
    premiumPromo: "AI 묵상 가이드와 주간 리포트 기능을 체험해보세요.",
    weeklySummaryTitle: "주간 요약",
    totalLogs: "전체 기록",
    dayUnit: "일",
    countUnit: "회",
    syncNow: "지금 동기화"
  },
  en: {
    appName: "GraceLog",
    home: "Log",
    calendar: "History",
    report: "Report",
    settings: "Settings",
    todayRecord: "Daily Reflection",
    selectBook: "Scripture",
    chapter: "Chapter",
    verse: "Verse",
    reflection: "Reflection (Observation)",
    application: "Application",
    prayer: "Prayer",
    save: "Save",
    aiHelp: "AI Assist",
    premium: "Premium",
    free: "Free Plan",
    premiumOnly: "Premium Feature",
    aiDisclaimer: "AI assistance is for reference only.",
    observation: "Observation",
    tags: "Tags",
    share: "Share",
    summary: "Summary",
    streak: "Streak",
    favorite: "Bookmarks",
    noRecords: "No records yet.",
    searchPlaceholder: "Search tags, keywords...",
    templateType: "Template",
    language: "Language",
    sync: "Cloud Sync",
    weeklyReport: "Weekly Report",
    stats: "Insights",
    recentTags: "Recent Tags",
    verseRange: "Verse range (e.g., 1-10)",
    switchPremium: "Try Premium (Free)",
    switchFree: "Switch to Free Plan",
    days: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    premiumPromo: "Experience AI meditation guides and weekly reports.",
    weeklySummaryTitle: "Weekly Summary",
    totalLogs: "Total Logs",
    dayUnit: "Days",
    countUnit: "Logs",
    syncNow: "Sync Now"
  }
};
